[package]
name = "bevy_basic_portals"
version = "0.1.0"
edition = "2021"
categories = ["game-engines", "graphics", "rendering"]
description = "A portal plugin for Bevy game engine"
exclude = ["helpers/"]
keywords = ["bevy", "portal", "gamedev"]
license = "EUPL-1.2-or-later"
readme = "README.md"
repository = "https://github.com/Selene-Amanita/bevy_basic_portals"
authors = ["Selene Amanita"]
[workspace]
members = [
    "helpers"
]
resolver = "2"

[dependencies]
bevy = { version = "0.10.*", default-features = false, features = [
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_render",
] }

[dev-dependencies]
bevy = { version = "0.10.*", default-features = false, features = [
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_render",
    "bevy_gilrs",
    "bevy_winit",
    "x11",
] }
helpers = { path = "helpers" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3